from __future__ import annotations

from enum import StrEnum


class LifecycleClass(StrEnum):
    PERMANENT_STATE = "PERMANENT_STATE"
    SOURCE = "SOURCE"
    FINAL = "FINAL"
    EXPORT = "EXPORT"
    PENDING = "PENDING"
    REGENERABLE = "REGENERABLE"
    CACHE = "CACHE"
    TEMP = "TEMP"
    REVIEW = "REVIEW"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


PINNED_LIFECYCLES = frozenset(
    {LifecycleClass.PERMANENT_STATE, LifecycleClass.SOURCE, LifecycleClass.FINAL,
     LifecycleClass.EXPORT, LifecycleClass.PENDING}
)


class CleanupClassification(StrEnum):
    SAFE_CANDIDATE = "SAFE_CANDIDATE"
    BLOCKED_ACTIVE_REFERENCE = "BLOCKED_ACTIVE_REFERENCE"
    BLOCKED_FINAL = "BLOCKED_FINAL"
    BLOCKED_EXPORT = "BLOCKED_EXPORT"
    BLOCKED_PENDING = "BLOCKED_PENDING"
    BLOCKED_UNKNOWN_OWNER = "BLOCKED_UNKNOWN_OWNER"
    BLOCKED_AMBIGUOUS_REFERENCE = "BLOCKED_AMBIGUOUS_REFERENCE"
    BLOCKED_SOURCE_POLICY = "BLOCKED_SOURCE_POLICY"
    LEGACY_REVIEW_REQUIRED = "LEGACY_REVIEW_REQUIRED"
