[server]
address = "127.0.0.1"
port = 8501
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "dashboard.proyaofficial.com"
serverPort = 443
gatherUsageStats = false
